### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [Shopify/liquid-tmbundle#3]
I would like to use your lexer at [github/linguist](https://github.com/github/linguist) to highlight Liquid code on GitHub but I don't know what licensing terms you're distributing it under.
Any chance you could pick one from here: http://choosealicense.com?

**Comment by pchaigno** [comment]
@andrew Did you get a chance to look into this?

**Comment by andrew** [comment]
@pchaigno the tmbundle was originally written by @bastilian, so it'd be best to ask him. He also has it hosted on his github, but with no license either: https://github.com/bastilian/validcode-textmate-bundles

**Comment by pchaigno** [comment]
Okay, thanks. I opened an issue at bastilian/validcode-textmate-bundles#1.
